### ISSUE TITLE
pdf theme's yml file not support [extends] attribute

### ISSUE THREAD

**Issue by someok** [asciidoctor/asciidoctor-gradle-plugin#442]
I use this plugin generate pdf file,  the theme's yml use `extends`, but it not work.

[extends description](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#extends):

> Currently, the base theme is always loaded first. Then, the files referenced by the extends key are loaded in order. Finally, the keys in the current file are loaded. Each time a theme is loaded, the keys are overlaid onto the keys from the previous theme.

My project structure:

![image](https://user-images.githubusercontent.com/1523082/62343160-44d48180-b51c-11e9-9126-803ea01ff19f.png)

Gradle:
```
    attributes 'pdf-fontsdir': file('data/fonts')
    attributes 'pdf-stylesdir': file('data/themes')
    attributes 'pdf-style': 'KaiGenGothicCN'
```

KaiGenGothicCN-theme.yml:
```
extends:
    - default
    - ./custom-theme.yml
font:
    catalog:
        KaiGen Gothic CN:
            normal: KaiGenGothicCN-Regular.ttf
            bold: KaiGenGothicCN-Bold.ttf
            italic: KaiGenGothicCN-Regular-Italic.ttf
            bold_italic: KaiGenGothicCN-Bold-Italic.ttf
        Roboto Mono:
            normal: RobotoMono-Regular.ttf
            bold: RobotoMono-Bold.ttf
            italic: RobotoMono-Italic.ttf
            bold_italic: RobotoMono-BoldItalic.ttf
    fallbacks:
        - KaiGen Gothic CN

base:
    align: left
    font_family: KaiGen Gothic CN

# literal is currently used for inline monospaced in prose and table cells
literal:
    font_family: Roboto Mono

```
